# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: delivery.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'delivery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65livery.proto\x12\x15\x61jin.edge.delivery.v1\"*\n\x0e\x45nqueueRequest\x12\x18\n\x10measurement_json\x18\x01 \x01(\x0c\"9\n\x0c\x45nqueueReply\x12\x16\n\x0emeasurement_id\x18\x01 \x01(\t\x12\x11\n\tduplicate\x18\x02 \x01(\x08\x32h\n\x0fMeasurementSink\x12U\n\x07\x45nqueue\x12%.ajin.edge.delivery.v1.EnqueueRequest\x1a#.ajin.edge.delivery.v1.EnqueueReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'delivery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENQUEUEREQUEST']._serialized_start=41
  _globals['_ENQUEUEREQUEST']._serialized_end=83
  _globals['_ENQUEUEREPLY']._serialized_start=85
  _globals['_ENQUEUEREPLY']._serialized_end=142
  _globals['_MEASUREMENTSINK']._serialized_start=144
  _globals['_MEASUREMENTSINK']._serialized_end=248
# @@protoc_insertion_point(module_scope)
